### ISSUE TITLE
Jenkins CI authentication

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-it/nubis-virtual-redirect#1]
Jenkins was integrated into this project recently. You can access it here:
https://ci.virtual-redirects.admin.us-west-2.virtual-redirects.nubis.allizom.org/

When attempting to login, it'll redirect to GitHub and after authorizing the application it'll redirect back to this URL:

https://ci.tlscanary.admin.us-west-2.virtual-redirects.nubis.allizom.org/

Notice the difference between projects (tlscanary vs. virtual-redirects).

**Comment by gozer** [comment]
My bad in setting up the OAuth stuff, fixed now

**Comment by danielhartnell** [comment]
Thanks!
